### ISSUE TITLE
error column 'price_level' can not be null

### ISSUE THREAD

**Issue by SASLEMON** [OPEN-DSI/ecommerceng#1]
Hi,
Worpress 4.8
WooCommerce 3.0.8
Nginx / Php 7 FPM / MariaDB + SSL

Dolibarr 5.0.1 (OVH Pro mutualisé)

Quand j'essaie d'ajouter une nouvelle boutique dans Configuration / ecommerceng, j'ai une erreur 
"error column 'price_level' can not be null"

Je l'ai temporairement contourné en ajoutant directement en BDD une valeur à price_level, puis en éditant dans config / ecommerceng le site ainsi créé

**Comment by kkhelifa-opendsi** [comment]
Bonjour,
J'ai corrigé le problème.
C'est une erreur de ma part, quand j'ai rajouté le champ 'price_level' dans la table, il devait accepter les valeurs NULL mais ce n'était pas le cas (il était à NOT NULL).
Cordialement,
