### ISSUE TITLE
Pas de synchro

### ISSUE THREAD

**Issue by SASLEMON** [OPEN-DSI/ecommerceng#2]
Worpress 4.8
WooCommerce 3.0.8
Nginx / Php 7 FPM / MariaDB + SSL

Dolibarr 5.0.1 (OVH Pro mutualisé)

Dans l'écran "ecommerce synchro", j'ai 2 boutons, "synchro détaillée" et "tout synchroniser", mais les 2 boutons amènent sur la même page, ou je peux juste rafraichir le comptage. Le bouton dessous qui sert visiblement à la synchro est grisé.

J'ai créé un produit dans la bonne catégorie sur doli, en espérant qu'il aille se mettre à jour dans mon WC, mais rien.
J'ai créé sur WC une catégorie "DemoA" (comme sur doli), mis un produit dedans, mais aucune synchro.

**Comment by kkhelifa-opendsi** [comment]
Bonjour,
A mon avis tu as un problème de connexion avec woocommerce.
Active les logs Dolibarr et tu t'en rendra compte.
J'en avait parlé dans la doc PDF.
Malheureusement le module de base ECommerceNg n'indique pas qu'il y a eu une erreur lors de la connexion. Donc, à part regarder dans les logs tu n'avais pas de moyen de le savoir.
Cordialement,

**Comment by SASLEMON** [comment]
Je viens de trouver ca dans le functions.php :
```
/* -- désactive XMLRPC -- */
add_filter('xmlrpc_enabled', '__return_false');
```

Pas sur que ca aide :)

**Comment by philippe-opendsi** [comment]
Bonjour, là ce doit être pour le XML RPC de Wordpress. A priori rien à voir. Je sens qu'il va falloir que l'on améliore le debug de la connexion :-) As-tu activer le module Journaux et traces de Dolibarr. Cela doit te générer par défaut un fichier dolibarr.log dans le dossier document de Dolibarr. C'est là que tu dois pouvoir retrouver les logs que la connexions Woocommerce. L'idéal est supprimer le fichier et ensuite de tester la connexion. Si quelqu'un d'autre se sert de Dolibarr en même temps, cela va bien sûr polluer la log. Poste nous le fichier de log avec la partie concernant la connexion WooCommerce. Merci

**Comment by SASLEMON** [comment]
Mes excuses, j'ai mélangé 2 fils :-/
Le XML n'a rien à voir, j'avais pas encore eu l'occasion de farfouiller les logs :)

Du coup, je me suis penché sur la question et voila le pastebin : https://pastebin.com/WZqxqgqG

J'ai 2 infos contracdictoire dedans :
-  eCommerceRemoteAccessWoocommerce connected with new Client ok.
-  eCommerceRemoteAccessWoocommerce::getProductToUpdate: Error: La clé secrète utilisateur est invalide. [woocommerce_api_authentication_error]-401-#0 /my/path/to/htdocs/ecommerceng/includes/WooCommerce/HttpClient/HttpClient.php(343): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Array)

J'aurais donc un souci de clé, je vais donc la changer pour voir...

EDIT = clée changée et modifiée, même erreur. Du coup, ben là, je sèche :)

EDIT 2 = en remplacant https://www.monsite.fr par https://www.monsite.fr/boutique, j'ai ce type d'erreur :
2017-06-19 16:37:02 WARNING 2.7.243.100     eCommerceRemoteAccessWoocommerce::getProductToUpdate: Syntax error-302-#0 /my/path/to/htdocs/ecommerceng/includes/WooCommerce/HttpClient/HttpClient.php(379): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()

**Comment by philippe-opendsi** [comment]
on va répondre d'ici jeudi, mais là charrette sur un chantier :-) Merci de patienter..

**Comment by philippe-opendsi** [comment]
Bonjour
Avez-vous essayé avec l'url /index.php/ (avec le patch correspondant pour Wordpress ?
Page 7 de la doc
