### ISSUE TITLE
Main synchronization setup - Customers category issue

### ISSUE THREAD

**Issue by ridersjin** [OPEN-DSI/ecommerceng#3]
Bonjour,

Lors de la configuration de ecommereng, je ne peux pas choisir le "customer category". La liste déroulante est vide. Comment faire ?

**Comment by SASLEMON** [comment]
Catégorie des produits :
C'est la catégorie des produits qui seront synchronisés avec le site.
Il faut préalablement activer le module « Libellés/Catégories » puis la créer dans le menu « Produits ».
- Catégorie des clients :
C'est la catégorie des tiers qui seront synchronisés avec le site.
Il faut préalablement activer le module « Libellés/Catégories » puis la créer dans le menu « Tiers ».

RTFM :)

**Comment by philippe-opendsi** [comment]
Bonjour
La doc est dans dossier "doc". du module. Pour l'instant pas très visible on est d'accord  :-) C'est dans les améliorations à venir

**Comment by ridersjin** [comment]
Bonjour,

Merci pour les informations. J'ai pu régler le probléme de customer cotegory.
