### ISSUE TITLE
Probléme ajout nouveau produit de Dolibarr vers Woocommerce ?

### ISSUE THREAD

**Issue by ridersjin** [OPEN-DSI/ecommerceng#4]
Bonjour,

La synchronisation des produits déja existant dans dolibarr et woocommerce fonctionne parfaitement. Toutefois lorsque j'ajoute un nouveau produit dans dolibarr, il ne s'ajoute pas dans woocommerce aprés synchronisation.
Quelqu'un aurait une solution pour moi ?

**Comment by philippe-opendsi** [comment]
Bonjour
Comme décrit sur 
https://wiki.dolibarr.org/index.php/Module_woocommerce_EN (on va ajouter le lien sur le README su dépot)
La synchro des produits de Dolibarr vers Woocommerce est TODO...

**Comment by ridersjin** [comment]
A ok. Vivement la futur version avec cette fonctionnalité :)
Si je veux ajouter un nouveau produit de dolibarr dans woocommerce manuellement, quels sont les paramétres à saisir dans la fiche produit woocommerce pour que la synchronisation fonctionne ?
J'ai essayé d'ajouter les paramétre dolibarr_id et dolibarr_type mais sans succés.
Actuellement la synchro de tous mes produits déja présent sur woocommerce et dolibarr fonctionne trés bien car la liaison avait déja été configuré avec le pluggin doliwoo.

**Comment by ridersjin** [comment]
J'ai finalement réussi à configurer manuellement la synchronisation. Il fallait aussi ajouter des informations dans la fiche produit sous dolibarr (public url, poids,).
