### ISSUE TITLE
Probléme Synchro 2nd woocommerce

### ISSUE THREAD

**Issue by ridersjin** [OPEN-DSI/ecommerceng#6]
Bonjour,

J'ai remarqué que lorsque l'on a plus de 2 woocommerce que l'on veut synchroniser depuis Dolibarr, seul le premier de la liste fonctionne. Pour les autres on a un message "504 Gateway Time-out
The server didn't respond in time."
Il y aurait t'il une solution à ce probléme ?

**Comment by philippe-opendsi** [comment]
Bonjour
Qui renvoit le 504 ? WooCommerce, Dolibarr ?

**Comment by ridersjin** [comment]
C'est Dolibarr quite renvoit le 504. Aprés avoir cliqué sur  tout synchronisé, l'erreur 504 s'affiche aprés une minute environs.

**Comment by philippe-opendsi** [comment]
Bonjour
Ce doit être un problème de timeout sur la synchro. Il faut augmenter le temps maximum d’exécution au niveau du PHP.  
C'est une partie que l'on va essayer d'améliorer avec le temps. Mais ce n'était pas vraiment prévu dans le module Ecommerceng pour Magento dont nous sommes parti. De même certains partie ne sont pas encore "optimisé" pour WooCommerce car nous avons dû nous couler dans le module original développé avec Magento.
