### ISSUE TITLE
Question about the Dollibarr installation

### ISSUE THREAD

**Issue by princeydev** [OPEN-DSI/ecommerceng#8]
Hi. Does the Dollibarr installation necessarily needs to be installed on a web server to connect with WooCommerce or can the Dollibarr just be on a Desktop connected to the Internet?
Thank you in advance.

**Comment by philippe-opendsi** [comment]
Hi
There's no need to have Dolibarr on the same server. But keep in mind that the synchronisation will take more time.
Regards
